// Additional employers and roles. `disciplines` drives the dependent dropdowns on the Target page.
const AERO = ["aerospace", "mechanical", "electrical", "materials", "computer-engineering", "industrial"];
const AUTO = ["mechanical", "electrical", "materials", "industrial", "computer-engineering", "chemical"];
const SEMI = ["electrical", "computer-engineering", "materials"];
const MED = ["biomedical", "mechanical", "materials", "electrical", "industrial", "chemical"];
const CIVIL = ["civil", "environmental", "mechanical", "industrial"];
const PROC = ["chemical", "mechanical", "environmental", "materials", "industrial", "civil"];
const SWE = ["computer-science", "computer-engineering"];
const IB = ["investment-banking"];
const CON = ["consulting"];

export const MORE_COMPANIES: { id: string; name: string; disciplines: string[] }[] = [
  // Engineering
  { id: "blue-origin", name: "Blue Origin", disciplines: AERO },
  { id: "rtx", name: "RTX (Raytheon, Pratt & Whitney, Collins)", disciplines: AERO },
  { id: "general-dynamics", name: "General Dynamics", disciplines: [...AERO, "civil"] },
  { id: "anduril", name: "Anduril", disciplines: [...AERO, "computer-science"] },
  { id: "rocket-lab", name: "Rocket Lab", disciplines: AERO },
  { id: "rivian", name: "Rivian", disciplines: AUTO },
  { id: "ford", name: "Ford Motor Company", disciplines: AUTO },
  { id: "gm", name: "General Motors", disciplines: AUTO },
  { id: "caterpillar", name: "Caterpillar", disciplines: ["mechanical", "electrical", "industrial", "materials", "chemical"] },
  { id: "john-deere", name: "John Deere", disciplines: ["mechanical", "electrical", "industrial", "computer-engineering", "materials"] },
  { id: "boston-dynamics", name: "Boston Dynamics", disciplines: ["mechanical", "electrical", "computer-engineering", "computer-science"] },
  { id: "honeywell", name: "Honeywell", disciplines: ["mechanical", "electrical", "chemical", "aerospace", "industrial", "computer-engineering"] },
  { id: "siemens", name: "Siemens", disciplines: ["electrical", "mechanical", "industrial", "computer-engineering"] },
  { id: "3m", name: "3M", disciplines: ["materials", "chemical", "mechanical", "industrial"] },
  { id: "intel", name: "Intel", disciplines: SEMI },
  { id: "texas-instruments", name: "Texas Instruments", disciplines: SEMI },
  { id: "amd", name: "AMD", disciplines: [...SEMI, "computer-science"] },
  { id: "qualcomm", name: "Qualcomm", disciplines: [...SEMI, "computer-science"] },
  { id: "medtronic", name: "Medtronic", disciplines: MED },
  { id: "johnson-and-johnson", name: "Johnson & Johnson (MedTech)", disciplines: MED },
  { id: "abbott", name: "Abbott", disciplines: MED },
  { id: "stryker", name: "Stryker", disciplines: MED },
  { id: "bechtel", name: "Bechtel", disciplines: [...CIVIL, "chemical", "electrical"] },
  { id: "aecom", name: "AECOM", disciplines: CIVIL },
  { id: "jacobs", name: "Jacobs", disciplines: [...CIVIL, "chemical"] },
  { id: "kiewit", name: "Kiewit", disciplines: CIVIL },
  { id: "dow", name: "Dow", disciplines: PROC },
  { id: "exxonmobil", name: "ExxonMobil", disciplines: PROC },
  { id: "chevron", name: "Chevron", disciplines: PROC },
  { id: "procter-gamble", name: "Procter & Gamble", disciplines: ["chemical", "industrial", "mechanical", "materials"] },
  // Computer science
  { id: "meta", name: "Meta", disciplines: SWE },
  { id: "netflix", name: "Netflix", disciplines: SWE },
  { id: "stripe", name: "Stripe", disciplines: SWE },
  { id: "uber", name: "Uber", disciplines: SWE },
  { id: "airbnb", name: "Airbnb", disciplines: SWE },
  { id: "databricks", name: "Databricks", disciplines: SWE },
  { id: "palantir", name: "Palantir", disciplines: SWE },
  { id: "openai", name: "OpenAI", disciplines: SWE },
  { id: "anthropic", name: "Anthropic", disciplines: SWE },
  { id: "salesforce", name: "Salesforce", disciplines: SWE },
  { id: "adobe", name: "Adobe", disciplines: SWE },
  { id: "oracle", name: "Oracle", disciplines: SWE },
  { id: "ibm", name: "IBM", disciplines: SWE },
  { id: "snowflake", name: "Snowflake", disciplines: SWE },
  { id: "intuit", name: "Intuit", disciplines: SWE },
  { id: "jane-street", name: "Jane Street", disciplines: SWE },
  { id: "citadel", name: "Citadel / Citadel Securities", disciplines: SWE },
  { id: "two-sigma", name: "Two Sigma", disciplines: SWE },
  { id: "hrt", name: "Hudson River Trading", disciplines: SWE },
  { id: "bloomberg", name: "Bloomberg", disciplines: SWE },
  { id: "capital-one", name: "Capital One", disciplines: SWE },
  { id: "bytedance", name: "TikTok / ByteDance", disciplines: SWE },
  { id: "atlassian", name: "Atlassian", disciplines: SWE },
  { id: "coinbase", name: "Coinbase", disciplines: SWE },
  { id: "doordash", name: "DoorDash", disciplines: SWE },
  // Investment banking and finance
  { id: "citi", name: "Citi", disciplines: IB },
  { id: "bank-of-america", name: "Bank of America", disciplines: IB },
  { id: "barclays", name: "Barclays", disciplines: IB },
  { id: "ubs", name: "UBS", disciplines: IB },
  { id: "deutsche-bank", name: "Deutsche Bank", disciplines: IB },
  { id: "rbc-capital-markets", name: "RBC Capital Markets", disciplines: IB },
  { id: "wells-fargo", name: "Wells Fargo", disciplines: IB },
  { id: "jefferies", name: "Jefferies", disciplines: IB },
  { id: "moelis", name: "Moelis & Company", disciplines: IB },
  { id: "pjt-partners", name: "PJT Partners", disciplines: IB },
  { id: "centerview", name: "Centerview Partners", disciplines: IB },
  { id: "perella-weinberg", name: "Perella Weinberg Partners", disciplines: IB },
  { id: "houlihan-lokey", name: "Houlihan Lokey", disciplines: IB },
  { id: "rothschild", name: "Rothschild & Co", disciplines: IB },
  { id: "william-blair", name: "William Blair", disciplines: IB },
  { id: "baird", name: "Baird", disciplines: IB },
  { id: "guggenheim", name: "Guggenheim Securities", disciplines: IB },
  { id: "kkr", name: "KKR", disciplines: IB },
  { id: "apollo", name: "Apollo", disciplines: IB },
  { id: "carlyle", name: "Carlyle", disciplines: IB },
  // Consulting
  { id: "pwc-strategy-and", name: "PwC / Strategy&", disciplines: CON },
  { id: "ey-parthenon", name: "EY-Parthenon", disciplines: CON },
  { id: "kpmg", name: "KPMG", disciplines: CON },
  { id: "oliver-wyman", name: "Oliver Wyman", disciplines: CON },
  { id: "lek", name: "L.E.K. Consulting", disciplines: CON },
  { id: "kearney", name: "Kearney", disciplines: CON },
  { id: "roland-berger", name: "Roland Berger", disciplines: CON },
  { id: "alvarez-marsal", name: "Alvarez & Marsal", disciplines: CON },
  { id: "fti-consulting", name: "FTI Consulting", disciplines: CON },
  { id: "huron", name: "Huron", disciplines: CON },
  { id: "zs-associates", name: "ZS Associates", disciplines: CON },
  { id: "guidehouse", name: "Guidehouse", disciplines: CON },
  { id: "slalom", name: "Slalom", disciplines: CON },
  { id: "capgemini-invent", name: "Capgemini Invent", disciplines: CON },
  { id: "west-monroe", name: "West Monroe", disciplines: CON },
];

export const MORE_ROLES: { id: string; name: string; keywords: string[]; disciplines: string[] }[] = [
  { id: "systems-engineer", name: "Systems engineer", keywords: ["systems engineer", "systems integration", "verification"], disciplines: ["aerospace", "mechanical", "electrical", "computer-engineering", "industrial"] },
  { id: "project-engineer", name: "Project / field engineer", keywords: ["project engineer", "field engineer", "construction engineer", "site engineer"], disciplines: ["civil", "environmental", "chemical", "industrial", "mechanical"] },
  { id: "ml-engineer", name: "Machine learning engineer", keywords: ["machine learning engineer", "ml engineer", "applied scientist", "research engineer"], disciplines: ["computer-science", "computer-engineering"] },
];
