import type { RubricCriterion } from "@/lib/rubric";

// ORIGINAL practice questions written for this project. All load as `draft`: nothing here is owner-approved,
// and no company association is a claim that the company asked the question.
export type SeedQuestion = {
  title: string;
  prompt: string;
  discipline: string;
  difficulty: 1 | 2 | 3;
  topics: string[];
  roles: string[];
  companies?: string[];
  ideal: string;
  core: string[];
  reasoning: string[];
  complete: string[];
  misconceptions: string[];
  alternatives?: string[];
  /** JSON CaseStage[]: present for staged case questions */
  caseData?: string;
  /** accuracy, reasoning, completeness, clarity — must total 100 */
  weights: [number, number, number, number];
};

export function buildRubric(q: SeedQuestion): RubricCriterion[] {
  const [wa, wr, wc, wl] = q.weights;
  return [
    {
      id: "technical-accuracy",
      name: "Technical accuracy",
      weight: wa,
      description: `Core facts are correct, especially: ${q.core.slice(0, 3).join("; ")}.`,
      anchors: {
        low: "Core statements are wrong or contradict standard theory.",
        mid: "Most core points are right but one is wrong or vague.",
        high: "All core points are correct and precisely stated.",
      },
      expectedConcepts: q.core,
      alternatives: q.alternatives ?? [],
      misconceptions: q.misconceptions,
    },
    {
      id: "reasoning",
      name: "Reasoning and trade-offs",
      weight: wr,
      description: `Explains why, not just what: ${q.reasoning.slice(0, 2).join("; ")}.`,
      anchors: {
        low: "Lists facts with no causal explanation.",
        mid: "Gives some causal links but skips key trade-offs or assumptions.",
        high: "Connects causes to consequences and weighs trade-offs explicitly.",
      },
      expectedConcepts: q.reasoning,
      alternatives: q.alternatives ?? [],
      misconceptions: [],
    },
    {
      id: "completeness",
      name: "Completeness",
      weight: wc,
      description: `Covers the practical details an interviewer would probe: ${q.complete.slice(0, 2).join("; ")}.`,
      anchors: {
        low: "Misses most of the expected supporting points.",
        mid: "Covers about half of the supporting points.",
        high: "Covers essentially all supporting points, including edge cases or verification.",
      },
      expectedConcepts: q.complete,
      alternatives: [],
      misconceptions: [],
    },
    {
      id: "clarity",
      name: "Clarity and structure",
      weight: wl,
      description: "States a direct answer, then explains in a logical order with correct terminology and units.",
      anchors: {
        low: "Disorganized or hard to follow.",
        mid: "Understandable but meanders or omits units/terms.",
        high: "Direct, ordered, and precise.",
      },
      expectedConcepts: ["direct answer stated first", "logical ordered explanation"],
      alternatives: [],
      misconceptions: [],
    },
  ];
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  {
    title: "Sizing a heat sink for a power module",
    prompt:
      "A 150 W power module must keep its junction at or below 85 °C in 40 °C ambient air. Walk through how you would decide whether a given heat sink is adequate, and what you would change if it is not.",
    discipline: "mechanical",
    difficulty: 2,
    topics: ["heat-transfer"],
    roles: ["thermal-engineer", "design-engineer"],
    companies: ["tesla", "nvidia", "apple"],
    ideal:
      "Use a thermal resistance network: Tj = Ta + P(Rjc + Rcs + Rsa). Allowed total is (85−40)/150 = 0.30 K/W. Subtract the datasheet junction-to-case and the interface (paste/pad) resistance to get the sink-to-ambient budget. Compare with the sink's rated Rsa at the real airflow and orientation. Natural convection gives low h (roughly 5–10 W/m²K), so area and fin spacing matter; if fins are too close the boundary layers merge and performance drops. If the budget is not met, add area, open fin pitch, add forced airflow, improve the interface, or spread heat with a heat pipe. Keep margin for altitude, dust, and tolerance, and confirm with a measurement or CFD.",
    core: ["thermal resistance network from junction to ambient", "allowed total resistance of about 0.30 K/W from the temperature rise and power", "subtract junction-to-case and interface resistance to find the sink budget"],
    reasoning: ["natural convection has low heat transfer coefficient so area is needed", "fin spacing trade-off between area and boundary layer merging", "forced convection or heat pipes as alternatives"],
    complete: ["check airflow and orientation of the real installation", "add design margin for altitude and fouling", "verify with test or CFD"],
    misconceptions: ["Adding more fins always lowers temperature", "Case temperature equals junction temperature"],
    alternatives: ["Using a transient thermal impedance analysis if the load is pulsed"],
    weights: [35, 30, 20, 15],
  },
  {
    title: "Diagnosing a shaft fatigue failure",
    prompt:
      "A steel shaft in service fails after several months. The fracture surface shows beach marks that start at the corner of a keyway. What happened, and how would you prevent it?",
    discipline: "mechanical",
    difficulty: 2,
    topics: ["fatigue-failure"],
    roles: ["design-engineer", "quality-engineer"],
    ideal:
      "Beach marks indicate progressive fatigue crack growth under cyclic loading, initiated at the keyway corner where stress concentration (Kt) is high. A rotating shaft under bending sees fully reversed stress each revolution. Prevention: increase the keyway fillet radius, use a profiled or sled-runner keyway, move to splines or an interference fit, improve surface finish, apply shot peening or cold rolling for compressive residual stress, and raise the section size or material strength. Check the endurance limit with Marin factors (surface, size, reliability) and a Goodman or similar criterion. Also verify actual loads, look for fretting or corrosion, and inspect for misalignment.",
    core: ["beach marks indicate fatigue crack propagation", "keyway corner is a stress concentration where the crack initiated", "rotating bending produces fully reversed cyclic stress"],
    reasoning: ["reducing stress concentration extends fatigue life", "surface treatment and residual stress affect crack initiation", "endurance limit is reduced by real-world factors"],
    complete: ["larger fillet radius or alternative to a sharp keyway", "shot peening or surface finish improvement", "verify real loads, misalignment, fretting or corrosion"],
    misconceptions: ["The shaft was simply overloaded once", "Fatigue only occurs above the yield strength"],
    weights: [35, 25, 25, 15],
  },
  {
    title: "Why use position tolerancing instead of plus/minus",
    prompt:
      "For a pattern of four mounting holes, why might you specify GD&T position with a datum reference frame instead of plus/minus coordinate tolerances? What does maximum material condition add?",
    discipline: "mechanical",
    difficulty: 2,
    topics: ["design-tolerancing"],
    roles: ["design-engineer", "quality-engineer"],
    ideal:
      "Plus/minus coordinates create a square tolerance zone and let errors stack along each axis, and they depend on how the part is measured. Position tolerance defines a cylindrical zone around the true position relative to functional datums, which is larger in the diagonal direction and matches how a fastener actually fits. Datum references fix how the part is located so inspection mirrors assembly. At maximum material condition, as the hole departs from its smallest size, a bonus tolerance is allowed, so more holes pass while still assembling. For fixed fasteners the allowed position tolerance is hole minus fastener at MMC (T = H − F).",
    core: ["position tolerance defines a cylindrical zone from true position", "plus/minus gives a square zone and ambiguous stack-up", "datum reference frame ties inspection to function and assembly"],
    reasoning: ["tolerance zone shape matches how a fastener fits", "bonus tolerance as the feature departs from maximum material", "functional design intent drives the tolerance choice"],
    complete: ["fixed fastener formula relating hole size and fastener size", "maximum material condition definition", "inspection with functional gauge or CMM"],
    misconceptions: ["Position tolerance is just a tighter plus/minus", "MMC means the largest hole"],
    weights: [35, 25, 25, 15],
  },
  {
    title: "Centrifugal pump cavitation",
    prompt: "A centrifugal pump is noisy and the impeller shows pitting. Explain what cavitation is, why it happens, and what you would change.",
    discipline: "mechanical",
    difficulty: 2,
    topics: ["fluid-mechanics"],
    roles: ["design-engineer", "process-engineer"],
    ideal:
      "Cavitation is the formation and violent collapse of vapor bubbles when local pressure at the impeller inlet drops below the fluid's vapor pressure. It happens when available NPSH is less than the pump's required NPSH. The collapse causes noise, vibration, performance loss, and pitting. Fixes: raise suction pressure or tank level, shorten and enlarge suction piping, remove restrictions, reduce fluid temperature (lower vapor pressure), lower the flow rate or speed, or choose a pump with a lower NPSHr or add an inducer. Throttle on the discharge side, not the suction side.",
    core: ["vapor bubbles form when local pressure falls below vapor pressure", "NPSH available below NPSH required", "bubble collapse causes pitting, noise and vibration"],
    reasoning: ["increasing suction pressure or reducing suction losses raises NPSHa", "lower fluid temperature reduces vapor pressure", "operating point and speed affect NPSHr"],
    complete: ["throttle on discharge not suction", "inducer or different pump selection", "check suction piping and strainer"],
    misconceptions: ["Cavitation is air leaking into the pump", "Throttling the suction valve fixes it"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Vibration peak at running speed",
    prompt: "A rotating machine shows a dominant vibration peak at 1× running speed. What are the likely causes and how would you narrow them down?",
    discipline: "mechanical",
    difficulty: 2,
    topics: ["statics-dynamics"],
    roles: ["design-engineer", "quality-engineer"],
    ideal:
      "A dominant 1× peak most often means rotor imbalance. Other candidates are a bent shaft, eccentric components, looseness, and resonance when running near a critical speed. Misalignment usually shows strong 2× content, looseness shows harmonics and sub-harmonics. To narrow it down, use phase measurements across bearings and directions (imbalance is in-phase radially, misalignment shows axial and 180° phase), check amplitude versus speed in a run-up to find resonance, and inspect mounting. Fix imbalance by field balancing with trial weights, then recheck.",
    core: ["1× peak is typically rotor imbalance", "misalignment shows strong 2× content", "looseness produces harmonics"],
    reasoning: ["phase measurements help distinguish imbalance from misalignment", "resonance depends on running speed relative to natural frequency", "verify the fix by re-measuring"],
    complete: ["run-up or coast-down to check critical speed", "trial weight balancing", "check mounting and bearings"],
    misconceptions: ["Any vibration means bearing failure", "A 1× peak cannot be caused by anything but imbalance"],
    weights: [35, 30, 20, 15],
  },
  {
    title: "Why a Hohmann transfer takes two burns",
    prompt: "Explain how a Hohmann transfer moves a spacecraft between two coplanar circular orbits. Why two burns, and what are the trade-offs against a faster transfer?",
    discipline: "aerospace",
    difficulty: 2,
    topics: ["orbital-mechanics"],
    roles: ["gnc-engineer", "propulsion-engineer"],
    companies: ["spacex", "lockheed-martin"],
    ideal:
      "A Hohmann transfer uses an elliptical orbit tangent to both circular orbits. The first tangential burn at the inner orbit raises apoapsis to the target radius. The spacecraft coasts half an ellipse, then a second tangential burn at apoapsis raises periapsis and circularizes. Two impulses are needed because a single burn leaves you on an ellipse that still passes through the starting point. It is the minimum-delta-v two-impulse transfer between coplanar circular orbits, but slow (half the transfer-orbit period). Faster transfers cost more delta-v. Plane changes are cheapest at low velocity, i.e. near apoapsis.",
    core: ["elliptical transfer orbit tangent to both circular orbits", "first burn raises apoapsis and second burn circularizes at apoapsis", "minimum delta-v two-impulse transfer between coplanar circular orbits"],
    reasoning: ["one burn leaves the spacecraft on an orbit that returns to the starting point", "transfer time equals half the period of the ellipse", "faster transfers cost more delta-v"],
    complete: ["burns are tangential, along the velocity direction", "plane changes are cheaper at low velocity", "delta-v budget drives propellant via the rocket equation"],
    misconceptions: ["The second burn is needed to slow down to descend", "Transfers are instantaneous"],
    weights: [35, 25, 25, 15],
  },
  {
    title: "Specific impulse versus thrust",
    prompt: "What is specific impulse, and how do you trade off a high-Isp engine against a high-thrust engine for a mission?",
    discipline: "aerospace",
    difficulty: 2,
    topics: ["propulsion"],
    roles: ["propulsion-engineer"],
    companies: ["spacex"],
    ideal:
      "Specific impulse is thrust divided by propellant weight flow, Isp = F / (mdot·g0), so it measures propellant efficiency in seconds. In the rocket equation, Δv = Isp·g0·ln(m0/mf), so higher Isp means less propellant for a given Δv. But high-Isp systems such as electric thrusters produce tiny thrust, so burns take weeks and they cannot lift off a planet. Launch needs high thrust (thrust-to-weight above 1) to limit gravity losses, which favors chemical engines. In-space transfers with long coast times can use high-Isp, low-thrust propulsion. Choice depends on mission time, power, mass, and Δv.",
    core: ["Isp is thrust divided by propellant weight flow", "rocket equation links delta-v to Isp and mass ratio", "electric propulsion has high Isp but low thrust"],
    reasoning: ["launch requires thrust-to-weight above one to limit gravity losses", "low-thrust burns take long and need power", "mission time versus propellant mass trade-off"],
    complete: ["units of seconds for Isp", "chemical for launch and electric for in-space cruise", "power and mass of the propulsion system"],
    misconceptions: ["Higher Isp always means a better engine", "Isp is the same as thrust"],
    weights: [35, 30, 20, 15],
  },
  {
    title: "What stall really is",
    prompt: "Why does a wing stall? How is stall related to airspeed, and what changes the stall speed?",
    discipline: "aerospace",
    difficulty: 1,
    topics: ["aerodynamics"],
    roles: ["design-engineer"],
    ideal:
      "A wing stalls when the angle of attack exceeds the critical angle (often around 15–18° for common airfoils) and the flow separates from the upper surface, so lift drops and drag rises. Stall is about angle of attack, not airspeed alone. Stall speed is the speed at which CLmax is needed to support the weight: Vs = sqrt(2W / (ρ S CLmax)). It rises with weight, load factor (turns, pull-ups) and altitude in true airspeed, and falls with flaps that raise CLmax. Recovery is to reduce angle of attack first.",
    core: ["flow separation at angle of attack above the critical angle", "stall is a function of angle of attack, not airspeed alone", "stall speed formula depends on weight, density, area and CLmax"],
    reasoning: ["more load factor or weight raises stall speed", "flaps increase CLmax and lower stall speed", "recovery requires reducing angle of attack"],
    complete: ["typical critical angle range", "lift drops and drag rises after separation", "accelerated stall in turns"],
    misconceptions: ["A wing only stalls when airspeed is too low", "Stall means the engine has stopped"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Gain margin and phase margin",
    prompt: "Explain gain margin and phase margin for a feedback control loop. Why do you need to look at both?",
    discipline: "aerospace",
    difficulty: 3,
    topics: ["gnc"],
    roles: ["gnc-engineer"],
    companies: ["spacex", "northrop-grumman"],
    ideal:
      "Both describe how close the open-loop frequency response is to the critical point −1 on the Nyquist plot. Gain margin is how much the loop gain could increase at the phase-crossover frequency (phase −180°) before the loop becomes unstable. Phase margin is how much additional phase lag could be tolerated at the gain-crossover frequency (gain 0 dB). Time delay and unmodeled dynamics add phase lag, so phase margin captures robustness to delay, while gain margin captures robustness to gain error or actuator uncertainty. Looking at one alone can mislead, since a loop can have a large gain margin and small phase margin or vice versa, and conditionally stable systems break simple rules. Typical targets are about 6 dB and 45°, with the Nyquist or sensitivity peak as a more complete check.",
    core: ["margins measure distance from the -1 point on the open-loop response", "gain margin is evaluated at the phase crossover frequency", "phase margin is evaluated at the gain crossover frequency"],
    reasoning: ["time delay and unmodeled dynamics reduce phase margin", "gain errors and actuator uncertainty reduce gain margin", "one margin alone can hide poor robustness"],
    complete: ["typical targets near 6 dB and 45 degrees", "sensitivity peak or Nyquist plot as a fuller check", "conditionally stable systems"],
    misconceptions: ["A large gain margin guarantees good damping", "Margins are only about the controller, not the plant"],
    weights: [35, 30, 20, 15],
  },
  {
    title: "Op-amp distortion at 200 kHz",
    prompt: "An inverting amplifier with a gain of −10 built with an op-amp rated at 1 MHz gain-bandwidth product distorts and loses gain at 200 kHz. Explain why and what you would do.",
    discipline: "electrical",
    difficulty: 2,
    topics: ["circuit-analysis"],
    roles: ["hardware-engineer"],
    companies: ["apple", "nvidia"],
    ideal:
      "The closed-loop bandwidth is roughly GBW divided by the noise gain, 1 MHz / (1 + 10) ≈ 91 kHz. At 200 kHz the open-loop gain is no longer large enough, so the closed-loop gain rolls off and phase shifts, which shows as attenuation and distortion. Slew rate can add distortion for large signals (required slew rate is 2π f Vpeak). Fixes: choose an op-amp with higher GBW, reduce the stage gain or split it across two stages, and check slew rate and stability with the feedback network and load.",
    core: ["closed-loop bandwidth is approximately GBW divided by noise gain", "about 91 kHz bandwidth for gain of 10 and 1 MHz GBW", "gain rolls off and phase shifts above the closed-loop bandwidth"],
    reasoning: ["finite open-loop gain at high frequency limits accuracy", "slew rate limits large-signal output", "splitting gain across stages trades noise and parts for bandwidth"],
    complete: ["choose an op-amp with higher GBW", "compute required slew rate", "check stability with the load and feedback network"],
    misconceptions: ["Bandwidth equals the GBW regardless of gain", "Distortion here is caused by the resistor values only"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "How a buck converter regulates",
    prompt: "Explain how a buck converter regulates its output voltage, and what sets the inductor ripple current. What trade-offs do you make choosing the inductor and switching frequency?",
    discipline: "electrical",
    difficulty: 2,
    topics: ["power-electronics"],
    roles: ["hardware-engineer"],
    companies: ["tesla", "apple"],
    ideal:
      "A switch chops the input and an LC filter averages it. In continuous conduction mode the output is Vout ≈ D·Vin, with D the duty cycle, and a feedback loop adjusts D to hold Vout. Inductor ripple is ΔIL = (Vin − Vout)·D / (L·fsw). A larger inductor or higher frequency lowers ripple, reducing output capacitor needs and peak current, but a bigger inductor costs size, resistance and slower transient response, and higher frequency raises switching losses. At light load the converter can enter discontinuous mode. A synchronous rectifier replaces the diode to cut conduction loss.",
    core: ["output voltage is about duty cycle times input voltage in continuous conduction", "inductor ripple current equation involves input minus output voltage, duty, inductance and frequency", "LC filter averages the switched waveform"],
    reasoning: ["larger inductance or frequency reduces ripple", "higher switching frequency increases switching loss", "feedback adjusts duty cycle to regulate"],
    complete: ["discontinuous conduction at light load", "synchronous rectification to reduce diode loss", "output capacitor ripple and transient response"],
    misconceptions: ["A buck converter can output higher voltage than the input", "Duty cycle sets output current"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Aliasing in a sampled sensor system",
    prompt: "What is aliasing? How do you prevent it in a system that samples a sensor signal with an ADC?",
    discipline: "electrical",
    difficulty: 1,
    topics: ["signals-systems"],
    roles: ["hardware-engineer", "firmware-engineer"],
    ideal:
      "Aliasing happens when a signal is sampled at less than twice its highest frequency component (Nyquist), so higher frequencies fold back and appear as false lower frequencies that cannot be separated afterwards. Prevent it by band-limiting before sampling with an analog anti-alias low-pass filter whose cutoff and roll-off ensure frequencies above fs/2 are attenuated below the ADC noise floor. Oversampling with a simpler analog filter followed by digital filtering and decimation is a common approach. Choose the sample rate with margin above the signal bandwidth.",
    core: ["frequencies above half the sampling rate fold back as false lower frequencies", "Nyquist requires sampling above twice the highest frequency", "aliasing cannot be removed after sampling"],
    reasoning: ["analog low-pass filter before the ADC removes out-of-band content", "oversampling relaxes the analog filter requirement", "filter roll-off must reach the noise floor by half the sample rate"],
    complete: ["digital filtering and decimation after oversampling", "choose sample rate with margin", "noise and interference as aliasing sources"],
    misconceptions: ["Aliasing can be filtered out digitally afterwards", "Sampling exactly at twice the frequency is always enough"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Sharing data between an ISR and the main loop",
    prompt: "Explain how to safely share a variable or buffer between an interrupt service routine and the main loop on a microcontroller.",
    discipline: "computer-engineering",
    difficulty: 2,
    topics: ["embedded-systems"],
    roles: ["firmware-engineer"],
    companies: ["tesla", "spacex"],
    ideal:
      "Mark the shared variable volatile so the compiler re-reads it, but volatile alone does not make multi-byte accesses atomic. On an 8- or 16-bit MCU a 32-bit read can be interrupted halfway and see a torn value. Protect it with a short critical section (disable interrupts, copy, restore) or use a single-producer single-consumer ring buffer where only the ISR writes the head and only the main loop writes the tail. Keep the ISR short: set a flag or push data and defer work to the main loop, avoid blocking calls and heavy printf. On an RTOS, use queues or semaphores from ISR-safe APIs. Consider memory barriers on multicore parts.",
    core: ["volatile prevents compiler caching but does not provide atomicity", "multi-byte reads can be torn by an interrupt", "critical section or ring buffer protects shared data"],
    reasoning: ["single-producer single-consumer ring buffer avoids locking", "keep the ISR short and defer work to the main loop", "disabling interrupts has latency cost so keep it brief"],
    complete: ["RTOS queues with ISR-safe APIs", "avoid blocking calls in ISR", "memory barriers on multicore"],
    misconceptions: ["volatile makes access atomic", "It is fine to do long processing inside the ISR"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Setup and hold time violations",
    prompt: "Describe setup and hold time violations in a synchronous digital design, how they differ, and how you fix each.",
    discipline: "computer-engineering",
    difficulty: 2,
    topics: ["digital-design"],
    roles: ["hardware-engineer"],
    companies: ["nvidia", "apple"],
    ideal:
      "Setup time is how long data must be stable before the active clock edge, hold time is how long it must remain stable after. A setup violation means data arrives too late, so the longest path is too slow; fix it by reducing logic depth, pipelining, optimizing the critical path, or lowering the clock frequency. A hold violation means data changes too soon after the edge, typically from short paths and clock skew; fix by adding delay (buffers) on the short path or fixing skew. Hold violations do not depend on clock frequency, so slowing the clock does not help. Violations can cause metastability, and signals crossing clock domains need synchronizers such as two flip-flops.",
    core: ["setup is data stability before the clock edge", "hold is data stability after the clock edge", "setup violation arises from too-slow long paths"],
    reasoning: ["hold violations come from short paths and skew", "lowering the clock frequency fixes setup but not hold", "pipelining reduces logic depth per stage"],
    complete: ["add delay buffers to fix hold", "metastability and two-flop synchronizers across clock domains", "static timing analysis finds violations"],
    misconceptions: ["Slowing the clock fixes hold violations", "Setup and hold are the same constraint"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Bending moment and deflection of a loaded beam",
    prompt: "A simply supported beam carries a uniformly distributed load. Where do the maximum shear and bending moment occur, and how does span length affect deflection?",
    discipline: "civil",
    difficulty: 1,
    topics: ["structural-analysis"],
    roles: ["structures-engineer"],
    ideal:
      "Reactions are wL/2 at each support. Maximum shear wL/2 occurs at the supports, and maximum bending moment wL²/8 occurs at midspan, where shear is zero. Maximum bending stress is σ = M·c/I. Midspan deflection is 5wL⁴/(384EI), so it grows with the fourth power of span and falls with stiffness EI. Doubling the span raises the deflection by sixteen times. Design checks both strength (stress) and serviceability (deflection limits), and a deeper section raises I strongly.",
    core: ["maximum bending moment of wL squared over eight at midspan", "maximum shear of wL over two at the supports", "midspan deflection is 5wL^4 over 384EI"],
    reasoning: ["deflection scales with the fourth power of span", "shear is zero where moment is maximum", "section stiffness EI controls deflection"],
    complete: ["bending stress equals M c over I", "check both strength and serviceability", "deeper section increases I"],
    misconceptions: ["Maximum moment occurs at the supports", "Deflection scales linearly with span"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Settlement in clay versus sand",
    prompt: "Why can a foundation on clay keep settling for months or years while one on sand settles quickly? Why does it matter for design?",
    discipline: "civil",
    difficulty: 2,
    topics: ["geotechnical"],
    roles: ["structures-engineer"],
    ideal:
      "Load first raises pore water pressure in saturated soil. Sand is highly permeable, so water drains quickly and the soil skeleton takes the load almost immediately; settlement is mostly immediate. Clay has very low permeability, so excess pore pressure dissipates slowly (consolidation), transferring load to the skeleton and compressing it over time. There is also secondary compression (creep). Differential settlement between parts of a structure can crack finishes and damage services, so design estimates total and differential settlement and rates. Mitigation: preloading or surcharge, wick drains, deep foundations, or lighter loads.",
    core: ["clay has low permeability so excess pore pressure dissipates slowly", "consolidation transfers load from pore water to the soil skeleton over time", "sand drains quickly so settlement is mostly immediate"],
    reasoning: ["differential settlement damages structures more than uniform settlement", "time rate depends on drainage path length and permeability", "secondary compression continues after primary consolidation"],
    complete: ["preloading or surcharge", "wick drains or deep foundations", "estimate total and differential settlement"],
    misconceptions: ["Clay is weaker than sand in every way", "Settlement stops once the structure is built"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "CSTR versus PFR for a first-order reaction",
    prompt: "For a first-order reaction at the same reactor volume and flow rate, which gives higher conversion, a CSTR or a PFR? Explain why, and when you might still choose a CSTR.",
    discipline: "chemical",
    difficulty: 2,
    topics: ["reaction-engineering"],
    roles: ["process-engineer"],
    ideal:
      "The PFR gives higher conversion for positive-order kinetics. In a PFR the concentration declines gradually along the length, so most of the reactor sees higher reactant concentration and hence faster rate. A CSTR is perfectly mixed so the whole volume sits at the low outlet concentration. For first-order kinetics with Da = kτ: X(PFR) = 1 − e^(−kτ) and X(CSTR) = kτ / (1 + kτ). A CSTR is chosen for easy temperature control, handling slurries, good mixing, or steady operation; several CSTRs in series approach PFR performance.",
    core: ["PFR gives higher conversion for positive-order reactions", "CSTR operates entirely at the low outlet concentration", "conversion expressions with Damkohler number"],
    reasoning: ["rate depends on concentration which declines along a PFR", "CSTRs in series approach PFR performance", "CSTR advantages in mixing and temperature control"],
    complete: ["X for PFR is one minus exp of minus k tau", "X for CSTR is k tau over one plus k tau", "handles slurries or exotherms"],
    misconceptions: ["A CSTR always gives better conversion because it is mixed", "Reactor volume is irrelevant to conversion"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Running a HAZOP study",
    prompt: "What is a HAZOP, and how would you run one for a new process unit?",
    discipline: "chemical",
    difficulty: 2,
    topics: ["process-safety"],
    roles: ["process-engineer"],
    ideal:
      "A HAZOP is a structured, team-based hazard identification method. Using P&IDs, you divide the process into nodes, define design intent, then apply guide words (no, more, less, reverse, as well as, other than) to parameters such as flow, pressure, temperature and level. For each deviation, the team identifies credible causes, consequences, existing safeguards, and whether more are needed, recording actions with owners. A facilitator and scribe lead a multidisciplinary team (process, operations, instrumentation, safety). Actions are tracked to closure and the study is revisited when the design changes.",
    core: ["structured team review using guide words applied to process parameters", "study nodes defined from P&IDs with a design intent", "identify causes, consequences and safeguards for each deviation"],
    reasoning: ["multidisciplinary team brings different knowledge", "recommendations assigned to owners and tracked", "re-run after design changes"],
    complete: ["examples of guide words such as no, more, less, reverse", "facilitator and scribe roles", "document and follow up actions"],
    misconceptions: ["A HAZOP is a one-time checklist by one engineer", "It quantifies failure probability"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Reading a stress-strain curve",
    prompt: "Interpret the engineering stress-strain curve of a ductile metal: what do yield strength, ultimate tensile strength and the post-peak drop mean?",
    discipline: "materials",
    difficulty: 1,
    topics: ["mechanical-properties"],
    roles: ["design-engineer", "quality-engineer"],
    ideal:
      "The initial linear region is elastic, with slope equal to Young's modulus E. Yield strength marks the onset of plastic deformation, often taken as the 0.2% offset. Beyond yield, strain hardening raises the stress to the ultimate tensile strength, the maximum engineering stress. After that, necking localizes deformation; the engineering stress falls because it is computed from the original area, while the true stress, using the shrinking area, keeps rising until fracture. Area under the curve relates to toughness, and elongation to ductility.",
    core: ["elastic slope is Young's modulus", "yield strength marks onset of plastic deformation, often 0.2 percent offset", "ultimate tensile strength is the maximum engineering stress"],
    reasoning: ["strain hardening raises stress before necking", "engineering stress uses original area so it falls after necking", "true stress keeps rising during necking"],
    complete: ["toughness relates to area under the curve", "ductility measured as elongation", "necking localizes deformation"],
    misconceptions: ["The material gets weaker after the peak", "Yield and ultimate strength are the same"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Quench and temper for a steel gear",
    prompt: "Why is a steel gear commonly quenched and then tempered? What is gained and lost at each step?",
    discipline: "materials",
    difficulty: 2,
    topics: ["phase-diagrams"],
    roles: ["design-engineer", "process-engineer"],
    ideal:
      "The steel is heated into the austenite range and quenched fast enough to avoid pearlite and bainite, forming martensite: a hard, strong, but brittle supersaturated structure with high internal stress, with a risk of distortion and quench cracks. Tempering at a moderate temperature lets carbon precipitate as carbides and relieves stress, trading some hardness and strength for much greater toughness and ductility. Higher tempering temperature gives lower hardness and higher toughness. The achievable depth of hardening depends on hardenability (alloying) and section size. For gear teeth, a hard wear-resistant surface with a tough core is the aim, sometimes with carburizing.",
    core: ["quenching austenite forms hard martensite", "martensite is brittle with high internal stress", "tempering reduces brittleness by precipitating carbides and relieving stress"],
    reasoning: ["tempering trades hardness for toughness", "cooling rate must avoid pearlite and bainite", "hardenability and section size limit through-hardening"],
    complete: ["distortion and quench crack risk", "higher tempering temperature lowers hardness", "carburizing for hard case and tough core"],
    misconceptions: ["Tempering makes steel harder", "Quenching alone is ideal for gears"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Stable process with a low Cpk",
    prompt: "A machining process is stable on its control chart but has a Cpk of 0.9. What does this tell you and what do you do about it?",
    discipline: "industrial",
    difficulty: 2,
    topics: ["quality-spc"],
    roles: ["quality-engineer", "process-engineer"],
    ideal:
      "A stable control chart means only common-cause variation, so the process is predictable. A Cpk of 0.9 means it is not capable: the spread plus offset from center leave too little room within the specification limits, so some parts will be out of spec (typical targets are 1.33 or higher). Check whether the mean is off-center (fix by re-centering, which raises Cpk toward Cp) or whether the spread itself is too wide (reduce variation through root-cause work, better fixturing, tooling, material). Do not adjust the process after every part (tampering). Validate the measurement system with gauge R&R, and only change the spec if the engineering requirement truly allows. Sort or inspect output while improving, and recompute the capability afterwards.",
    core: ["stable chart means only common-cause variation", "Cpk below target means the process is not capable of meeting spec", "Cpk accounts for both spread and centering"],
    reasoning: ["re-center if the mean is offset, reduce variation if the spread is too large", "tampering with the process increases variation", "specification changes need engineering justification"],
    complete: ["measurement system analysis or gauge R&R", "typical capability target such as 1.33", "inspect or sort output while improving"],
    misconceptions: ["In control means within specification", "Widening the control limits fixes capability"],
    weights: [35, 30, 20, 15],
  },
  {
    title: "Finding the bottleneck on a production line",
    prompt: "A production line makes 40 units per hour but the plan requires 55. How do you find the bottleneck and increase throughput?",
    discipline: "industrial",
    difficulty: 2,
    topics: ["lean-manufacturing"],
    roles: ["process-engineer"],
    companies: ["tesla"],
    ideal:
      "Map the flow and measure the real cycle time and capacity of each station, including downtime, changeovers and yield loss. The bottleneck is the station with the lowest effective capacity; look for WIP piling up in front of it and downstream stations starving. Throughput of the line equals the bottleneck's rate, so improving non-bottlenecks does not help. Use Theory of Constraints: identify, exploit (eliminate idle time, breaks, defects at the constraint), subordinate other steps to it, then elevate (add capacity, parallel station, faster process) and re-check since the constraint moves. Confirm gains with measured throughput.",
    core: ["bottleneck is the station with the lowest effective capacity", "line throughput equals the bottleneck rate", "WIP accumulates before the bottleneck and downstream stations starve"],
    reasoning: ["improving non-bottleneck stations does not raise throughput", "exploit the constraint before spending on capacity", "the constraint moves after improvement"],
    complete: ["measure cycle times, downtime, changeovers and yield", "theory of constraints steps", "verify with measured throughput"],
    misconceptions: ["Speed up every station equally", "The slowest worker is the bottleneck"],
    weights: [35, 30, 20, 15],
  },
  {
    title: "Biocompatibility evaluation for an implant",
    prompt: "What does biocompatibility evaluation involve for a new implantable device, and what determines which tests you need?",
    discipline: "biomedical",
    difficulty: 2,
    topics: ["biomaterials-devices"],
    roles: ["design-engineer", "quality-engineer"],
    ideal:
      "Biological evaluation is risk-based and follows the ISO 10993 series, driven by the nature and duration of body contact (here an implant in tissue or blood, long term). It starts with material and chemical characterization and a biological evaluation plan, using existing data where the same material and processing have a history. Typical endpoints include cytotoxicity, sensitization, irritation, systemic toxicity, genotoxicity, implantation effects, and hemocompatibility if blood contacts. Sterilization residuals and degradation products matter. Regulators such as the FDA expect this within the submission, and any material or process change can require re-evaluation.",
    core: ["ISO 10993 series guides biological evaluation", "contact type and duration determine required endpoints", "chemical characterization and a biological evaluation plan"],
    reasoning: ["risk-based approach reuses existing data for known materials", "changes in material or process can trigger re-evaluation", "sterilization residuals and degradation products matter"],
    complete: ["examples of endpoints such as cytotoxicity, sensitization, implantation", "hemocompatibility when in contact with blood", "regulatory submission expectations"],
    misconceptions: ["A single cytotoxicity test is enough", "Using a biocompatible material guarantees a biocompatible device"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Design controls and traceability",
    prompt: "Explain design controls in medical device development. What is the difference between verification and validation, and why does traceability matter?",
    discipline: "biomedical",
    difficulty: 2,
    topics: ["biomaterials-devices"],
    roles: ["quality-engineer", "design-engineer"],
    ideal:
      "Design controls are a structured process: user needs lead to design inputs (requirements), design outputs (drawings, specs, code), verification, validation, design reviews, transfer, and change control, all documented in a design history file. Verification asks 'did we build the device right?' by testing outputs against inputs. Validation asks 'did we build the right device?' by confirming the device meets user needs in realistic use, often with users. Traceability links each user need to requirements, design elements, and tests, so gaps, impact of changes, and evidence for auditors are visible. Frameworks include FDA 21 CFR 820 and ISO 13485.",
    core: ["user needs lead to design inputs, outputs, verification and validation", "verification checks outputs against inputs while validation checks against user needs", "design history file documents the process"],
    reasoning: ["traceability exposes gaps and change impact", "validation under realistic use with users", "design reviews at stages"],
    complete: ["21 CFR 820 or ISO 13485 mention", "design transfer and change control", "risk management links"],
    misconceptions: ["Verification and validation are the same activity", "Documentation can be written after the device ships"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Conventional drinking water treatment",
    prompt: "Outline the steps of conventional drinking water treatment and say what each step removes or achieves.",
    discipline: "environmental",
    difficulty: 1,
    topics: ["water-treatment"],
    roles: ["process-engineer"],
    ideal:
      "Raw water is screened, then coagulation adds a coagulant such as alum to destabilize suspended particles, and flocculation gently mixes so they form larger flocs. Sedimentation lets flocs settle out. Filtration through sand or granular activated carbon removes remaining particles and some organics, and turbidity is monitored. Disinfection with chlorine, chloramine, UV or ozone inactivates pathogens, with a chlorine residual maintained in the distribution system. pH adjustment controls corrosion. Disinfection byproducts from chlorine reacting with organics must be balanced against pathogen control.",
    core: ["coagulation destabilizes particles and flocculation forms flocs", "sedimentation settles flocs and filtration removes remaining particles", "disinfection inactivates pathogens with a residual in distribution"],
    reasoning: ["disinfection byproducts versus pathogen control trade-off", "turbidity monitoring shows filter performance", "pH and corrosion control protect the distribution system"],
    complete: ["screening at intake", "examples of coagulants such as alum", "UV or ozone as alternative disinfection"],
    misconceptions: ["Filtration alone makes water safe", "Chlorine removes suspended solids"],
    weights: [40, 20, 25, 15],
  },
  {
    title: "Two numbers that sum to a target",
    prompt: "Given an array of integers and a target, determine whether any two different elements sum to the target. Compare approaches and their complexity.",
    discipline: "computer-science",
    difficulty: 1,
    topics: ["algorithms"],
    roles: ["software-engineer"],
    companies: ["google", "amazon", "microsoft"],
    ideal:
      "Brute force checks every pair in O(n²) time and O(1) space. A hash set lets you do one pass: for each x, check whether target − x is already in the set, then add x. That is O(n) time and O(n) space. If the array may be sorted (or sorting is acceptable), sort and use two pointers from both ends: O(n log n) time, O(1) extra space. Handle edge cases: using the same element twice (only valid if it appears twice), duplicates, negative numbers, empty or single-element input, and overflow. Choose by whether memory or sorted order matters.",
    core: ["brute force is quadratic time", "hash set gives linear time with linear space", "sorting with two pointers is n log n time and constant space"],
    reasoning: ["time versus space trade-off between approaches", "check complement before inserting the current element", "sorted input makes two pointers natural"],
    complete: ["same element cannot be used twice unless duplicated", "negative numbers and duplicates", "empty or single element input"],
    misconceptions: ["Hash lookups are always constant time in the worst case", "Sorting is free"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Detecting a cycle in a linked list",
    prompt: "How do you detect a cycle in a singly linked list? Explain why your method terminates and what it costs.",
    discipline: "computer-science",
    difficulty: 2,
    topics: ["algorithms"],
    roles: ["software-engineer"],
    ideal:
      "Floyd's tortoise and hare uses two pointers: slow moves one node per step and fast moves two. If there is no cycle, fast reaches null and you stop. If there is a cycle, both end up inside it, and fast gains one node per step on slow, so the gap shrinks by one each iteration and they must meet. Time is O(n), space O(1). A simpler alternative stores visited nodes in a hash set: O(n) time and O(n) space. To find the cycle start, reset one pointer to the head and advance both one step at a time; they meet at the entry node.",
    core: ["slow pointer moves one step and fast pointer moves two", "fast reaching null means no cycle", "linear time and constant space"],
    reasoning: ["relative speed of one node per step guarantees a meeting inside a cycle", "hash set alternative costs linear space", "reset one pointer to the head to find the cycle start"],
    complete: ["handle empty list and single node", "state complexity explicitly", "explain why they must meet"],
    misconceptions: ["Fast and slow can skip over each other forever inside a cycle", "A hash set is the only way"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Design a URL shortener",
    prompt: "Design a URL shortening service. Cover the API, how you generate short codes, storage, and how you would scale it.",
    discipline: "computer-science",
    difficulty: 2,
    topics: ["systems-design"],
    roles: ["software-engineer"],
    companies: ["google", "amazon"],
    ideal:
      "API: create (POST long URL, optional custom alias and expiry) returning a short code, and redirect (GET /code returning 301 or 302). The workload is read-heavy. Generate codes with a unique counter or ID service encoded in base62, or a hash with collision checks; avoid guessable sequential codes if privacy matters. Store code to URL in a key-value or relational store with a unique index. Cache hot codes in memory (e.g. Redis) with TTL; use 302 if you need analytics or edits, 301 if permanent caching is acceptable. Scale with read replicas or partitioning by code, stateless app servers behind a load balancer, rate limiting for abuse, async analytics, and replication for availability.",
    core: ["create and redirect API endpoints", "unique short code generation using counter with base62 or hash with collision handling", "key-value storage keyed by short code"],
    reasoning: ["read-heavy workload motivates caching", "301 versus 302 redirect trade-off", "partition or replicate for scale and availability"],
    complete: ["expiry and custom aliases", "rate limiting and abuse prevention", "analytics handled asynchronously"],
    misconceptions: ["Hashing the URL always avoids collisions", "A single database server is enough at scale"],
    weights: [35, 30, 20, 15],
  },
  {
    title: "When an index makes things worse",
    prompt: "Indexes usually speed up queries. In what situations can adding an index slow a database down or fail to help?",
    discipline: "computer-science",
    difficulty: 2,
    topics: ["databases"],
    roles: ["software-engineer"],
    ideal:
      "Every index must be updated on insert, update and delete, so write-heavy tables pay extra latency and storage. Indexes on low-selectivity columns (e.g. a boolean) often are not used since scanning is cheaper, and the planner may ignore them. Tiny tables are faster to scan. Too many indexes bloat storage, memory and maintenance. Composite indexes only help when the query matches the leftmost-column order, and functions on a column can prevent use of the index. Verify with EXPLAIN and real workload measurements, and drop unused indexes.",
    core: ["indexes must be updated on writes", "low selectivity columns often are not helped by an index", "indexes consume storage and memory"],
    reasoning: ["planner may choose a scan when it is cheaper", "composite index column order matters", "functions on indexed columns can prevent index use"],
    complete: ["use EXPLAIN to verify", "drop unused indexes", "small tables scan faster"],
    misconceptions: ["More indexes are always better", "An index is always used if it exists"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "ACID and isolation levels",
    prompt: "Explain ACID, and how transaction isolation levels trade correctness against concurrency.",
    discipline: "computer-science",
    difficulty: 3,
    topics: ["databases"],
    roles: ["software-engineer"],
    ideal:
      "Atomicity: a transaction applies fully or not at all. Consistency: it moves the database between valid states respecting constraints. Isolation: concurrent transactions do not see each other's partial effects. Durability: committed data survives crashes, usually via a write-ahead log. Weaker isolation allows anomalies: dirty reads (read uncommitted), non-repeatable reads, and phantoms. Read committed prevents dirty reads, repeatable read prevents non-repeatable reads (phantoms depend on the engine), and serializable prevents all of them as if transactions ran one at a time. Stronger levels reduce concurrency and can cause more blocking or aborts. Many engines use MVCC so readers do not block writers.",
    core: ["atomicity, consistency, isolation and durability definitions", "dirty reads, non-repeatable reads and phantoms", "read committed, repeatable read and serializable levels"],
    reasoning: ["stronger isolation reduces concurrency", "MVCC lets readers avoid blocking writers", "durability via write-ahead logging"],
    complete: ["serializable behaves as if transactions ran one at a time", "retry or abort handling at higher isolation", "choose level per workload"],
    misconceptions: ["Serializable has no performance cost", "Consistency in ACID means the same as in CAP"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Deadlock conditions and prevention",
    prompt: "What is a deadlock? What conditions are required for it, and how can you prevent or recover from one?",
    discipline: "computer-science",
    difficulty: 2,
    topics: ["concurrency-os"],
    roles: ["software-engineer", "firmware-engineer"],
    ideal:
      "A deadlock is when threads wait on each other forever. It needs all four Coffman conditions: mutual exclusion, hold and wait, no preemption, and circular wait. Example: thread A holds lock 1 and wants lock 2 while thread B holds lock 2 and wants lock 1. Prevent by breaking a condition: impose a global lock ordering (no circular wait), acquire all locks at once or avoid nested locks (no hold and wait), use try-lock with timeout and back-off (allow release), or use lock-free structures. Detect with a wait-for graph and recover by aborting or rolling back a participant. Logging lock order and timeouts helps debugging.",
    core: ["threads wait on each other forever", "mutual exclusion, hold and wait, no preemption and circular wait", "two locks acquired in opposite order example"],
    reasoning: ["breaking any one condition prevents deadlock", "global lock ordering removes circular wait", "timeouts and try-lock allow recovery"],
    complete: ["wait-for graph detection", "avoid nested locks", "debugging with lock-order logging"],
    misconceptions: ["Deadlock only happens with mutexes and never with other resources", "Only one of the four conditions is needed"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "Process versus thread",
    prompt: "What is the difference between a process and a thread, and how do you decide which to use?",
    discipline: "computer-science",
    difficulty: 1,
    topics: ["concurrency-os"],
    roles: ["software-engineer"],
    ideal:
      "A process has its own address space and resources, while threads within a process share memory and open files but each has its own stack and registers. Threads are cheaper to create and switch and communicate through shared memory, but need synchronization to avoid races, and a crash or memory corruption can take down the whole process. Processes give isolation and fault containment but communicate through IPC (pipes, sockets, shared memory) and cost more. Use threads for shared-data parallelism and low latency, processes for isolation, security boundaries or fault tolerance. Language runtimes such as a global interpreter lock can limit thread parallelism.",
    core: ["processes have separate address spaces while threads share memory", "threads have their own stack and registers", "processes communicate through IPC"],
    reasoning: ["shared memory requires synchronization to avoid races", "isolation gives fault containment", "threads are cheaper to create and switch"],
    complete: ["examples of IPC mechanisms", "crash in one thread can take down the process", "language runtime limits such as a global interpreter lock"],
    misconceptions: ["Threads are always faster", "Processes cannot communicate"],
    weights: [40, 25, 20, 15],
  },
  {
    title: "From URL to rendered page",
    prompt: "Describe what happens from the moment a user types a URL into a browser until the page appears.",
    discipline: "computer-science",
    difficulty: 1,
    topics: ["networking"],
    roles: ["software-engineer"],
    ideal:
      "The browser parses the URL and checks caches. DNS resolves the hostname to an IP (browser, OS, resolver caches, then recursive lookup). The browser opens a TCP connection (three-way handshake) or uses QUIC, then negotiates TLS for HTTPS (certificate validation, key exchange). It sends an HTTP request; the server (often behind a CDN or load balancer) processes it and returns a response with status, headers and body. The browser parses HTML, fetches CSS, JS and images (reusing connections, HTTP/2 multiplexing), builds the DOM and CSSOM, runs scripts, and renders. Caching headers can skip steps.",
    core: ["DNS resolves the hostname to an IP address", "TCP handshake then TLS negotiation for HTTPS", "HTTP request and response then the browser parses and renders"],
    reasoning: ["caching at several layers can skip steps", "CDN or load balancer sits in front of the server", "subresources fetched over reused connections"],
    complete: ["certificate validation in TLS", "DOM and CSSOM construction", "HTTP/2 or HTTP/3 improvements"],
    misconceptions: ["DNS happens after the TCP connection", "The page is rendered before the HTML is received"],
    weights: [40, 20, 25, 15],
  },
  {
    title: "Caching a read-heavy service",
    prompt: "How would you add caching to a read-heavy service, and what are the risks around invalidation and consistency?",
    discipline: "computer-science",
    difficulty: 3,
    topics: ["systems-design"],
    roles: ["software-engineer"],
    companies: ["amazon", "google"],
    ideal:
      "Use cache-aside: on a read, check the cache, on a miss load from the database and populate with a TTL. Writes either invalidate or update the key (write-through or write-behind have different durability trade-offs). Invalidation is hard: stale reads happen when invalidation races with reads, so choose TTLs based on staleness tolerance and consider versioned keys. Cache stampede on a hot expiring key can overwhelm the database; mitigate with request coalescing, locks, jittered TTLs, or refresh-ahead. Choose an eviction policy such as LRU, size memory, design keys carefully, and monitor hit rate and latency. Consistency versus latency is the core trade-off.",
    core: ["cache-aside read path with TTL", "invalidation on writes and risk of stale reads", "cache stampede on hot keys"],
    reasoning: ["TTL chosen from staleness tolerance", "request coalescing or jittered TTL mitigates stampede", "consistency versus latency trade-off"],
    complete: ["write-through versus write-behind", "eviction policy such as LRU", "monitor hit rate and latency"],
    misconceptions: ["Caching never returns stale data", "Cache invalidation is trivial"],
    weights: [35, 30, 20, 15],
  },
];
