// Additional topics so each discipline has enough breadth for a deep question bank.
export const EXTRA_TOPICS: { id: string; name: string; disciplineId: string; keywords: string[] }[] = [
  { id: "thermodynamics", name: "Thermodynamics", disciplineId: "mechanical", keywords: ["thermodynamic", "cycle", "entropy", "rankine", "brayton"] },
  { id: "machine-design", name: "Machine design", disciplineId: "mechanical", keywords: ["machine design", "bearing", "gear", "bolt", "shaft", "spring"] },
  { id: "manufacturing-processes", name: "Manufacturing processes", disciplineId: "mechanical", keywords: ["machining", "casting", "welding", "injection molding", "cnc"] },
  { id: "mechatronics-controls", name: "Controls & mechatronics", disciplineId: "mechanical", keywords: ["mechatronics", "pid", "actuator", "sensor", "servo"] },
  { id: "vibrations", name: "Vibrations", disciplineId: "mechanical", keywords: ["vibration", "natural frequency", "damping", "resonance"] },
  { id: "flight-dynamics", name: "Flight dynamics & stability", disciplineId: "aerospace", keywords: ["flight dynamics", "stability", "trim", "longitudinal", "dutch roll"] },
  { id: "aerospace-structures", name: "Aerospace structures", disciplineId: "aerospace", keywords: ["airframe", "monocoque", "buckling", "composite layup", "margin of safety"] },
  { id: "spacecraft-systems", name: "Spacecraft systems", disciplineId: "aerospace", keywords: ["spacecraft", "attitude", "power system", "thermal control", "link budget"] },
  { id: "compressible-flow", name: "Compressible flow", disciplineId: "aerospace", keywords: ["compressible", "shock", "mach", "nozzle", "supersonic"] },
  { id: "electromagnetics", name: "Electromagnetics", disciplineId: "electrical", keywords: ["electromagnetic", "maxwell", "transmission line", "antenna", "waveguide"] },
  { id: "analog-electronics", name: "Analog electronics", disciplineId: "electrical", keywords: ["transistor", "bjt", "mosfet", "amplifier", "feedback", "noise"] },
  { id: "control-theory", name: "Control theory", disciplineId: "electrical", keywords: ["control theory", "transfer function", "bode", "root locus", "state space"] },
  { id: "power-systems", name: "Power systems", disciplineId: "electrical", keywords: ["power system", "transformer", "three-phase", "grid", "protection relay"] },
  { id: "communications", name: "Communications", disciplineId: "electrical", keywords: ["modulation", "snr", "channel", "ofdm", "error correction"] },
  { id: "structural-design", name: "Structural design", disciplineId: "civil", keywords: ["reinforced concrete", "steel design", "load combination", "connection", "lrfd"] },
  { id: "hydraulics-hydrology", name: "Hydraulics & hydrology", disciplineId: "civil", keywords: ["hydrology", "open channel", "stormwater", "culvert", "manning"] },
  { id: "transportation", name: "Transportation engineering", disciplineId: "civil", keywords: ["traffic", "highway", "pavement", "intersection", "level of service"] },
  { id: "construction-management", name: "Construction management", disciplineId: "civil", keywords: ["construction", "scheduling", "critical path", "cost estimate", "site safety"] },
  { id: "civil-materials", name: "Civil engineering materials", disciplineId: "civil", keywords: ["concrete", "asphalt", "aggregate", "steel grade", "curing"] },
  { id: "chem-thermodynamics", name: "Chemical thermodynamics", disciplineId: "chemical", keywords: ["vle", "fugacity", "equation of state", "gibbs", "phase equilibrium"] },
  { id: "mass-transfer", name: "Mass transfer & separations", disciplineId: "chemical", keywords: ["distillation", "absorption", "extraction", "membrane", "mass transfer"] },
  { id: "heat-exchangers", name: "Heat exchangers", disciplineId: "chemical", keywords: ["heat exchanger", "lmtd", "shell and tube", "fouling", "ntu"] },
  { id: "process-control", name: "Process control", disciplineId: "chemical", keywords: ["process control", "pid tuning", "feedforward", "cascade", "control valve"] },
  { id: "fluid-transport", name: "Fluid transport", disciplineId: "chemical", keywords: ["pump", "piping", "pressure drop", "compressor", "two-phase"] },
  { id: "polymers-ceramics", name: "Polymers & ceramics", disciplineId: "materials", keywords: ["polymer", "ceramic", "glass transition", "thermoplastic", "sintering"] },
  { id: "corrosion", name: "Corrosion", disciplineId: "materials", keywords: ["corrosion", "galvanic", "passivation", "cathodic protection", "oxidation"] },
  { id: "characterization", name: "Materials characterization", disciplineId: "materials", keywords: ["xrd", "sem", "tem", "spectroscopy", "metallography"] },
  { id: "composites", name: "Composites", disciplineId: "materials", keywords: ["composite", "carbon fiber", "laminate", "matrix", "delamination"] },
  { id: "diffusion-kinetics", name: "Diffusion & kinetics", disciplineId: "materials", keywords: ["diffusion", "nucleation", "kinetics", "grain growth", "fick"] },
  { id: "operations-research", name: "Operations research", disciplineId: "industrial", keywords: ["linear programming", "optimization", "queueing", "simplex", "scheduling"] },
  { id: "supply-chain", name: "Supply chain & inventory", disciplineId: "industrial", keywords: ["supply chain", "inventory", "logistics", "demand planning", "safety stock"] },
  { id: "ergonomics", name: "Ergonomics & safety", disciplineId: "industrial", keywords: ["ergonomic", "human factors", "workplace safety", "niosh", "osha"] },
  { id: "forecasting-simulation", name: "Forecasting & simulation", disciplineId: "industrial", keywords: ["forecast", "simulation", "monte carlo", "time series", "regression"] },
  { id: "project-management", name: "Project management", disciplineId: "industrial", keywords: ["project management", "pert", "gantt", "risk register", "earned value"] },
  { id: "biomechanics", name: "Biomechanics", disciplineId: "biomedical", keywords: ["biomechanics", "gait", "joint", "tissue mechanics", "orthopedic"] },
  { id: "physiology", name: "Physiology for engineers", disciplineId: "biomedical", keywords: ["physiology", "cardiovascular", "respiratory", "renal", "homeostasis"] },
  { id: "biosignals", name: "Biosignals & instrumentation", disciplineId: "biomedical", keywords: ["ecg", "eeg", "biosignal", "electrode", "medical instrumentation"] },
  { id: "medical-imaging", name: "Medical imaging", disciplineId: "biomedical", keywords: ["mri", "ct", "ultrasound", "x-ray", "imaging"] },
  { id: "regulatory-affairs", name: "Regulatory & quality systems", disciplineId: "biomedical", keywords: ["fda", "510(k)", "iso 14971", "design controls", "capa"] },
  { id: "air-quality", name: "Air quality", disciplineId: "environmental", keywords: ["air quality", "emissions", "scrubber", "particulate", "plume"] },
  { id: "groundwater-hydrology", name: "Groundwater & hydrology", disciplineId: "environmental", keywords: ["groundwater", "aquifer", "darcy", "well", "watershed"] },
  { id: "waste-management", name: "Solid & hazardous waste", disciplineId: "environmental", keywords: ["landfill", "waste", "recycling", "hazardous", "incineration"] },
  { id: "remediation", name: "Site remediation", disciplineId: "environmental", keywords: ["remediation", "contaminant", "bioremediation", "pump and treat", "soil vapor"] },
  { id: "environmental-regulation", name: "Environmental regulation", disciplineId: "environmental", keywords: ["epa", "clean air act", "clean water act", "permit", "impact assessment"] },
  { id: "computer-architecture", name: "Computer architecture", disciplineId: "computer-engineering", keywords: ["cpu", "pipeline", "isa", "cache", "out-of-order"] },
  { id: "memory-systems", name: "Memory systems", disciplineId: "computer-engineering", keywords: ["dram", "sram", "virtual memory", "tlb", "memory hierarchy"] },
  { id: "interfaces-protocols", name: "Interfaces & protocols", disciplineId: "computer-engineering", keywords: ["uart", "can bus", "pcie", "usb", "ethernet"] },
  { id: "vlsi", name: "VLSI & chip design", disciplineId: "computer-engineering", keywords: ["vlsi", "cmos", "asic", "synthesis", "place and route"] },
  { id: "hardware-debug", name: "Hardware debugging & test", disciplineId: "computer-engineering", keywords: ["oscilloscope", "logic analyzer", "jtag", "signal integrity", "bring-up"] },
  { id: "data-structures", name: "Data structures", disciplineId: "computer-science", keywords: ["linked list", "heap", "tree", "hash map", "trie"] },
  { id: "oop-design", name: "Object-oriented & software design", disciplineId: "computer-science", keywords: ["object-oriented", "design pattern", "solid", "inheritance", "interface"] },
  { id: "security", name: "Security", disciplineId: "computer-science", keywords: ["security", "encryption", "xss", "injection", "authentication"] },
  { id: "web-apis", name: "Web & APIs", disciplineId: "computer-science", keywords: ["rest", "api", "http", "graphql", "frontend"] },
  { id: "testing-reliability", name: "Testing & reliability", disciplineId: "computer-science", keywords: ["unit test", "ci/cd", "observability", "incident", "sre"] },
  { id: "machine-learning", name: "Machine learning basics", disciplineId: "computer-science", keywords: ["machine learning", "overfitting", "gradient descent", "classification", "neural network"] },
];
