import type { SeedQuestion } from "../seed-questions";
import type { Q } from "./types";

// Sensible default roles per topic so role filters and ranking work for the bank without per-question tagging.
export const TOPIC_ROLES: Record<string, string[]> = {
  "heat-transfer": ["thermal-engineer"],
  thermodynamics: ["thermal-engineer", "design-engineer"],
  "fluid-mechanics": ["design-engineer", "process-engineer"],
  "statics-dynamics": ["design-engineer"],
  "fatigue-failure": ["design-engineer", "quality-engineer"],
  "design-tolerancing": ["design-engineer", "quality-engineer"],
  "machine-design": ["design-engineer"],
  "manufacturing-processes": ["process-engineer", "quality-engineer"],
  "mechatronics-controls": ["design-engineer", "hardware-engineer", "systems-engineer"],
  vibrations: ["design-engineer"],
  propulsion: ["propulsion-engineer"],
  "orbital-mechanics": ["gnc-engineer"],
  gnc: ["gnc-engineer"],
  "flight-dynamics": ["gnc-engineer", "design-engineer", "systems-engineer"],
  aerodynamics: ["design-engineer"],
  "compressible-flow": ["propulsion-engineer", "design-engineer"],
  "aerospace-structures": ["structures-engineer", "systems-engineer"],
  "spacecraft-systems": ["design-engineer", "hardware-engineer", "systems-engineer"],
  "circuit-analysis": ["hardware-engineer"],
  "analog-electronics": ["hardware-engineer"],
  "power-electronics": ["hardware-engineer"],
  "signals-systems": ["hardware-engineer", "firmware-engineer"],
  electromagnetics: ["hardware-engineer"],
  "control-theory": ["gnc-engineer", "hardware-engineer"],
  "power-systems": ["hardware-engineer"],
  communications: ["hardware-engineer"],
  "embedded-systems": ["firmware-engineer", "systems-engineer"],
  "digital-design": ["hardware-engineer"],
  "computer-architecture": ["hardware-engineer"],
  "memory-systems": ["hardware-engineer"],
  "interfaces-protocols": ["firmware-engineer", "hardware-engineer"],
  vlsi: ["hardware-engineer"],
  "hardware-debug": ["hardware-engineer", "firmware-engineer", "systems-engineer"],
  "structural-analysis": ["structures-engineer"],
  "structural-design": ["structures-engineer", "project-engineer"],
  geotechnical: ["structures-engineer", "project-engineer"],
  "hydraulics-hydrology": ["process-engineer", "project-engineer"],
  transportation: ["process-engineer", "project-engineer"],
  "construction-management": ["process-engineer", "quality-engineer", "project-engineer"],
  "civil-materials": ["quality-engineer", "structures-engineer", "project-engineer"],
  "reaction-engineering": ["process-engineer"],
  "process-safety": ["process-engineer"],
  "chem-thermodynamics": ["process-engineer"],
  "mass-transfer": ["process-engineer"],
  "heat-exchangers": ["process-engineer", "thermal-engineer"],
  "process-control": ["process-engineer", "systems-engineer"],
  "fluid-transport": ["process-engineer"],
  "mechanical-properties": ["design-engineer", "quality-engineer"],
  "phase-diagrams": ["process-engineer", "quality-engineer"],
  "polymers-ceramics": ["design-engineer", "process-engineer"],
  corrosion: ["quality-engineer", "design-engineer"],
  characterization: ["quality-engineer"],
  composites: ["design-engineer", "structures-engineer"],
  "diffusion-kinetics": ["process-engineer"],
  "quality-spc": ["quality-engineer"],
  "lean-manufacturing": ["process-engineer", "systems-engineer"],
  "operations-research": ["process-engineer", "project-engineer"],
  "supply-chain": ["process-engineer"],
  ergonomics: ["quality-engineer", "process-engineer"],
  "forecasting-simulation": ["process-engineer"],
  "project-management": ["process-engineer", "project-engineer"],
  "biomaterials-devices": ["design-engineer", "quality-engineer"],
  biomechanics: ["design-engineer"],
  physiology: ["design-engineer"],
  biosignals: ["hardware-engineer", "design-engineer"],
  "medical-imaging": ["hardware-engineer"],
  "regulatory-affairs": ["quality-engineer"],
  "water-treatment": ["process-engineer", "project-engineer"],
  "air-quality": ["process-engineer"],
  "groundwater-hydrology": ["process-engineer"],
  "waste-management": ["process-engineer"],
  remediation: ["process-engineer", "project-engineer"],
  "environmental-regulation": ["quality-engineer", "process-engineer"],
  algorithms: ["software-engineer"],
  "data-structures": ["software-engineer"],
  "systems-design": ["software-engineer"],
  databases: ["software-engineer"],
  "concurrency-os": ["software-engineer", "firmware-engineer"],
  networking: ["software-engineer"],
  "oop-design": ["software-engineer"],
  security: ["software-engineer"],
  "web-apis": ["software-engineer"],
  "testing-reliability": ["software-engineer"],
  "machine-learning": ["software-engineer", "ml-engineer"],
  "ib-accounting": ["ib-analyst"],
  "ib-valuation": ["ib-analyst", "equity-research", "private-equity"],
  "ib-ma": ["ib-analyst"],
  "ib-lbo": ["private-equity", "ib-analyst"],
  "ib-markets": ["markets-trader", "ib-analyst"],
  "ib-fit": ["ib-analyst", "markets-trader", "equity-research", "private-equity"],
  "case-structuring": ["business-analyst", "strategy-associate"],
  "market-sizing": ["business-analyst", "strategy-associate"],
  "case-strategy": ["business-analyst", "strategy-associate"],
  "case-math": ["business-analyst", "strategy-associate"],
  "brain-teasers": ["business-analyst", "strategy-associate"],
  "consulting-fit": ["business-analyst", "strategy-associate"],
};

export function toSeed(discipline: string, q: Q): SeedQuestion {
  const half = Math.ceil(q.c.length / 2);
  const roles = q.r ?? TOPIC_ROLES[q.tp] ?? [];
  return {
    title: q.t,
    prompt: q.p,
    discipline,
    difficulty: q.d,
    topics: [q.tp, ...(q.tp2 ? [q.tp2] : [])],
    roles,
    ideal: q.i,
    core: q.c.slice(0, half),
    reasoning: q.k,
    complete: q.c.length > half ? q.c.slice(half) : q.c.slice(-1),
    misconceptions: q.m && q.m.length ? q.m : ["Stating conclusions without the reasoning behind them"],
    weights: [40, 25, 20, 15],
  };
}
